"""The render-bound cue side-car, and rebasing its cues onto a Short.

Why this file exists at all: a long export with burned-in subtitles is
*permanently* captioned. There is no honest way to take those pixels back out —
OCR, inpainting, crop or blur all destroy picture the user rendered on purpose —
so a Short that wants its own large captions needs the caption **text and
timing** as data, not as pixels.

The ``.srt`` files beside an export are user artifacts: they can be renamed,
edited, deleted or regenerated by hand, and a Short must never depend on finding
one. This side-car is the machine copy instead:

* written once, at long-render time, from the exact ``Timeline.cues`` that
  render used — so it carries the real word-level timing improvements verbatim;
* versioned, with a content hash over the cue payload;
* bound to the clean master's checksum, so it can never be paired with a
  different video.

Rebasing is the other half. A Short is a re-ordered subset of the source
timeline, so every cue has to be clipped to the spans that were actually cut and
moved onto the output's own clock.
"""

from __future__ import annotations

import hashlib
import json
import logging
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path

from pydantic import Field, ValidationError as PydanticValidationError

from app.errors import ErrorCode, NotFoundError, ValidationError
from app.models.base import CamelModel
from app.timing.subtitles import Cue

logger = logging.getLogger("evb.shorts.cues")

#: Bumped whenever the meaning of a field below changes. Readers refuse anything
#: newer and keep accepting everything older they know about.
CUE_SIDECAR_SCHEMA_VERSION = 1

CUE_SIDECAR_SUFFIX = "-shorts-cues.json"

#: A cue clipped to less than this is a sliver at a cut boundary, not a caption.
#: One frame at 60 fps is 16.7 ms; 120 ms is the shortest flash worth drawing.
MIN_REBASED_CUE_SECONDS = 0.12


class SidecarCue(CamelModel):
    """One caption, on the *source* video's absolute timeline."""

    index: int
    unit_id: str
    start_seconds: float = Field(ge=0.0)
    end_seconds: float = Field(ge=0.0)
    lines: list[str] = Field(default_factory=list)

    @property
    def text(self) -> str:
        return "\n".join(self.lines)

    @property
    def duration_seconds(self) -> float:
        return max(0.0, self.end_seconds - self.start_seconds)


class CueSidecar(CamelModel):
    """Every caption of one finished render, as immutable data."""

    schema_version: int = CUE_SIDECAR_SCHEMA_VERSION
    project_slug: str
    render_job_id: str = ""
    #: SHA-256 of the clean master these cues are timed against. The pairing is
    #: checked before any Short uses them.
    clean_master_sha256: str
    total_duration_seconds: float
    #: How the timing was produced, for the provenance summary in a Short's
    #: manifest: "measured-words", "estimated", or "mixed".
    timing_source: str = "unknown"
    #: Digest of the cue payload alone. Two renders that produced identical
    #: captions produce the same value, whatever else changed around them.
    content_hash: str = ""
    cues: list[SidecarCue] = Field(default_factory=list)
    written_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))


class CueSidecarRef(CamelModel):
    """What the render manifest records about the side-car it wrote."""

    filename: str
    schema_version: int = CUE_SIDECAR_SCHEMA_VERSION
    #: SHA-256 of the side-car *file*, so a hand-edited one is caught.
    sha256: str
    #: SHA-256 of the cue payload, which is what actually changes the pixels.
    content_hash: str
    cue_count: int = 0
    timing_source: str = "unknown"


# --- writing ---------------------------------------------------------------


def cue_content_hash(cues: list[SidecarCue]) -> str:
    """Digest of exactly what will be drawn, and when."""
    payload = [
        {
            "unitId": cue.unit_id,
            "start": round(cue.start_seconds, 4),
            "end": round(cue.end_seconds, 4),
            "lines": list(cue.lines),
        }
        for cue in cues
    ]
    return hashlib.sha256(
        json.dumps(payload, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode(
            "utf-8"
        )
    ).hexdigest()


def build_sidecar(
    *,
    project_slug: str,
    cues: list[Cue],
    cues_by_unit: dict[str, list[Cue]],
    clean_master_sha256: str,
    total_duration_seconds: float,
    render_job_id: str = "",
    timing_source: str = "unknown",
) -> CueSidecar:
    """Turn the timeline's cues into the immutable side-car payload.

    ``cues_by_unit`` only supplies the unit each cue belongs to; the times come
    straight from the cue objects, untouched, because those are the ones the
    render actually burned or exported.
    """
    owner: dict[tuple[int, float, float], str] = {
        (cue.index, cue.start_seconds, cue.end_seconds): unit_id
        for unit_id, unit_cues in cues_by_unit.items()
        for cue in unit_cues
    }

    entries = [
        SidecarCue(
            index=cue.index,
            unit_id=owner.get((cue.index, cue.start_seconds, cue.end_seconds), ""),
            start_seconds=round(cue.start_seconds, 4),
            end_seconds=round(cue.end_seconds, 4),
            lines=list(cue.lines),
        )
        for cue in cues
    ]
    sidecar = CueSidecar(
        project_slug=project_slug,
        render_job_id=render_job_id,
        clean_master_sha256=clean_master_sha256,
        total_duration_seconds=round(total_duration_seconds, 4),
        timing_source=timing_source,
        cues=entries,
    )
    sidecar.content_hash = cue_content_hash(entries)
    return sidecar


def sidecar_path_for(clean_master: Path) -> Path:
    """Where the side-car for a clean master lives. Always beside it."""
    return clean_master.with_name(f"{clean_master.stem}{CUE_SIDECAR_SUFFIX}")


def write_sidecar(sidecar: CueSidecar, target: Path) -> CueSidecarRef:
    """Write the side-car atomically and describe it for the manifest."""
    from app.shorts.manifest import sha256_file

    target.parent.mkdir(parents=True, exist_ok=True)
    tmp = target.with_suffix(".json.tmp")
    tmp.write_text(sidecar.model_dump_json(indent=2), "utf-8")
    tmp.replace(target)

    logger.info("wrote cue side-car %s (%d cues)", target.name, len(sidecar.cues))
    return CueSidecarRef(
        filename=target.name,
        schema_version=sidecar.schema_version,
        sha256=sha256_file(target),
        content_hash=sidecar.content_hash,
        cue_count=len(sidecar.cues),
        timing_source=sidecar.timing_source,
    )


# --- reading and verifying --------------------------------------------------


def load_sidecar(path: Path, ref: CueSidecarRef | None = None) -> CueSidecar:
    """Read a side-car, refusing anything that is not exactly the one recorded.

    Every failure here is a *stale source* failure, not a caption failure: the
    only safe answer is to tell the user to re-render, never to quietly fall back
    to the burned-in source and double-caption the Short.
    """
    from app.shorts.manifest import sha256_file

    if not path.is_file():
        raise NotFoundError(
            ErrorCode.SHORT_CLEAN_SOURCE_STALE,
            f"Bu videonun altyazı verisi ('{path.name}') bulunamadı.",
            details=f"beklenen konum: {path}",
            suggestion=(
                "Uzun videoyu, altyazısız kopya hazırlama seçeneği açıkken yeniden oluşturun. "
                "Büyük altyazılar için o sırada yazılan altyazı verisi gerekir."
            ),
        )

    if ref is not None:
        digest = sha256_file(path)
        if digest != ref.sha256:
            raise ValidationError(
                ErrorCode.SHORT_CLEAN_SOURCE_STALE,
                f"Bu videonun altyazı verisi ('{path.name}') yazıldığından beri değişmiş.",
                details=f"kayıtlı sha256 {ref.sha256}\ndosya    sha256 {digest}",
                suggestion=(
                    "Uzun videoyu yeniden oluşturun. Altyazı verisi tek bir videoya bağlıdır "
                    "ve elle düzenlenemez."
                ),
            )

    try:
        raw = json.loads(path.read_text("utf-8"))
    except (json.JSONDecodeError, OSError) as exc:
        raise ValidationError(
            ErrorCode.SHORT_CLEAN_SOURCE_STALE,
            f"Altyazı verisi '{path.name}' okunamadı.",
            details=str(exc),
        ) from exc

    version = raw.get("schemaVersion", raw.get("schema_version"))
    if isinstance(version, int) and version > CUE_SIDECAR_SCHEMA_VERSION:
        raise ValidationError(
            ErrorCode.UNSUPPORTED_SCHEMA_VERSION,
            f"Altyazı verisi '{path.name}' uygulamanın daha yeni bir sürümüyle yazılmış.",
            details=(
                f"dosya sürümü {version}, desteklenen sürüm {CUE_SIDECAR_SCHEMA_VERSION}"
            ),
        )

    try:
        sidecar = CueSidecar.model_validate(raw)
    except PydanticValidationError as exc:
        raise ValidationError(
            ErrorCode.SHORT_CLEAN_SOURCE_STALE,
            f"Altyazı verisi '{path.name}' beklenen biçimde değil.",
            details=str(exc)[:2000],
            suggestion="Uzun videoyu yeniden oluşturun; yeni video taze altyazı verisi yazar.",
        ) from exc

    expected = ref.content_hash if ref is not None else sidecar.content_hash
    actual = cue_content_hash(sidecar.cues)
    if actual != expected:
        raise ValidationError(
            ErrorCode.SHORT_CLEAN_SOURCE_STALE,
            f"Altyazı verisi '{path.name}' kendi içinde tutarsız.",
            details=f"kayıtlı {expected}\nhesaplanan {actual}",
            suggestion="Tutarlı altyazı verisi için uzun videoyu yeniden oluşturun.",
        )
    return sidecar


# --- rebasing ---------------------------------------------------------------


@dataclass(frozen=True)
class RebasedCue:
    """One caption, clipped to a cut and placed on the Short's own clock."""

    start_seconds: float
    end_seconds: float
    lines: list[str]
    unit_id: str
    group_index: int
    #: Where it came from, kept for the log and for debugging a bad cut.
    source_start_seconds: float
    source_end_seconds: float

    @property
    def text(self) -> str:
        return "\n".join(self.lines)

    @property
    def duration_seconds(self) -> float:
        return max(0.0, self.end_seconds - self.start_seconds)


def rebase_cues(
    cues: list[SidecarCue],
    groups,  # noqa: ANN001 - list[ShortGroupPlan]; imported lazily to avoid a cycle
    *,
    min_duration: float = MIN_REBASED_CUE_SECONDS,
) -> list[RebasedCue]:
    """Map source cues onto the Short's output timeline.

    The rules, in the order they matter:

    * **Groups play in the user's chosen order.** ``plan.groups`` is already in
      output order, so the output cursor simply walks them; a reversed selection
      reverses the captions with it.
    * **Only cues that intersect a cut survive.** A cue wholly outside every cut
      is dropped, and one straddling a trim boundary is clipped to it, so a
      caption can never appear over picture it does not belong to.
    * **Contiguous sections are one group**, so a cue spanning a preserved
      in-source transition is carried through whole, exactly once — the merge
      happened in the planner, and nothing here re-splits it.
    * **Overlaps are preserved.** Two sections overlap during a dissolve, so
      their cues can genuinely overlap by a fraction of a second. Those are left
      alone to alpha-composite over each other, the same way their pictures do.
    * **Slivers are dropped.** A cue clipped to a few milliseconds at a cut edge
      would flash for under a frame.
    """
    rebased: list[RebasedCue] = []
    cursor = 0.0

    for group in groups:
        start = float(group.start_seconds)
        end = float(group.end_seconds)
        for cue in cues:
            clipped_start = max(cue.start_seconds, start)
            clipped_end = min(cue.end_seconds, end)
            if clipped_end - clipped_start < min_duration:
                continue
            rebased.append(
                RebasedCue(
                    start_seconds=round(cursor + (clipped_start - start), 4),
                    end_seconds=round(cursor + (clipped_end - start), 4),
                    lines=list(cue.lines),
                    unit_id=cue.unit_id,
                    group_index=group.index,
                    source_start_seconds=round(clipped_start, 4),
                    source_end_seconds=round(clipped_end, 4),
                )
            )
        cursor = round(cursor + float(group.duration_seconds), 4)

    # Stable sort by start time only: cues that legitimately overlap keep the
    # order they were found in, so the later scene's caption draws on top.
    rebased.sort(key=lambda cue: cue.start_seconds)
    return rebased
